name: Try building Envoy images
on:
  push:
    branches: [envoy]

jobs:
  test-envoy:
    name: Try to build envoy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'cilium/proxy'
          path: proxy
      - uses: docker://docker.io/cilium/image-maker:bc81755ec8f6c5afcb10a416cef73f99a35fee2c
        name: Register binfmt from multi-platform builds
        with:
          entrypoint: docker
          args: run --privileged linuxkit/binfmt:5d33e7346e79f9c13a73c6952669e47a53b063d4 
      - uses: docker://docker.io/cilium/image-maker:bc81755ec8f6c5afcb10a416cef73f99a35fee2c
        name: Run make docker-image-builder
        with:
          entrypoint: make
          args: -C proxy docker-image-builder
